name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour de v2 à v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Mise à jour de v2 à v3
        with:
          node-version: '20'  # Utilisation de Node.js 20 (version récente supportée)

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release