name: Renovate Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Exécuter Renovate avec spécification du dépôt
      - name: Run Renovate --autodiscover
        uses: renovatebot/github-action@v41.0.4
        with:
          token: ${{ secrets.GH_TOKEN }}
