name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Toutes les 5 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Renovate
        run: npx renovate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LOG_LEVEL: debug
