name: Run Renovate

on:
  schedule:
    # Lancer tous les jours à 00:00 UTC
    - cron: '*/5 * * * *' # Exécution toutes les 2 minutes
  workflow_dispatch: # Permet de lancer manuellement
  push:
    paths:
      - "renovate.json"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Renovate
      - name: Install Renovate
        run: npm install -g renovate

      # Exécuter Renovate
      - name: Run Renovate
        run: renovate
