name: Renovate Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Exécuter Renovate en mode autodiscover
      - name: Run Renovate with autodiscover
        run: npx renovate --autodiscover
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Assurez-vous que ce token ait les bonnes permissions
