name: Renovate Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer et exécuter Renovate avec autodiscover
      - name: Run Renovate with autodiscover
        run: |
          npx renovate --autodiscover
        env:
          GITHUB_COM_TOKEN: ${{ secrets.gh_token_renovate }}
