name: Renovate Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  # schedule: # Tâche cron désactivée, mais peut être réactivée si nécessaire
  #   - cron: '0 0 1 * *'  # Exécution le premier jour de chaque mois

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer et exécuter Renovate avec autodiscover
      - name: Run Renovate with autodiscover
        run: |
          npx renovate --autodiscover
        env:
          GITHUB_COM_TOKEN: ${{ secrets.gh_token_renovate }}
