name: Renovate Workflow

on:
  push: 
    branches:
      - main
  pull_request: 
  workflow_dispatch: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      # Cloner le dépôt actuel
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          
      # Exécuter Renovate
      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          token: ${{ secrets.GH_TOKEN }}
